// Generated by CoffeeScript 1.6.3
(function() {
  var assert;

  assert = require('assert');

  suite('Test', function() {
    test('coffee', function(done, server) {
      server["eval"](function() {
        var e;
        e = some_fun();
        return emit('fun_called', e);
      });
      return server.once('fun_called', function(e) {
        assert.equal(e, 'some fun called');
        return done();
      });
    });
    return test('coffee package', function(done, server) {
      server["eval"](function() {
        var e;
        e = Spomet.find('some phrase');
        return emit('found', e);
      });
      return server.once('found', function(e) {
        assert.equal(e.length, 1);
        return done();
      });
    });
  });

}).call(this);
